config/routes.rb
Rails.application.routes.draw do

  get 'authors' => 'books#authors'

  get 'books/new' => 'books#new'

  get 'books_by_author' => 'books#books_by_author'

  resources :books
  devise_for :users

  root 'books#index'
  # root 'books#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  validates :title, presence: { message: " must be entered, please!" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authors

  protected

  def authors
    @authors = Author.order(:id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @authors = Author.order(:name)
  end

  # GET /books/1/edit
  def edit
    @authors = Author.order(:name)
  end

  # GET /books/welcome
  def welcome
  end

  # GET /authors
  def authors
    @authors = Author.order(:name)
  end

  # GET /books_by_author?id=1
  def books_by_author
    @books = Book.order(:title)
    @author = Author.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="container-fluid">
  <div class="row" style="color: #000;">

    <%= form_with(model: book, local: true) do |form| %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :book_title, class: 'form-control' %>
      </div>

<!--       <div class="field form-group">
        <%#= form.label :author_id %>
        <%#= form.number_field :author_id, id: :book_author_id, class: 'form-control' %>
      </div> -->

      <div class="form-group">
        <%= form.label :author_id %>
        <%# form.text_field :author_id, id: :name, class: 'form-control' %>

        <%= form.select :author_id, @authors.collect { |author| [ author.name, author.id ] }, { include_blank: "Please select an author" } %>
      </div>

      <div class="actions form-group">
        <%= form.submit %>
      </div>
    <% end %>

  </div>
</div>

app/views/books/authors.html.erb
<div class="container">
  <div class="row main">

    <p id="notice"><%= notice %></p>

    <div class="panel-heading">

        <h1>All Our Authors</h1>

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Books</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @authors.order(:name).each do |author| %>
              <tr>
                <td><%= author.name %></td>
                <td><%= link_to author.books.count, books_by_author_path(id: author.id), class: 'btn btn-default' %></td>
                <!-- <td><%#= link_to author.books.count, books_by_author_path(id: author.id) %></td> -->
                <!-- <td><%#= link_to 'Show', authors_path, class: 'btn btn-default' %></td> -->
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'Books', books_path, class: 'btn btn-info' %>

      </div>

  </div>
</div>

app/views/books/books_by_author.html.erb
<div class="container">
  <div class="row main text-center">
    <h1>These are <%= @author.name %>'s books:</h1>

      <% @author.books.count do |t| %>
        <%= t.title %><br>
      <% end %>

      <br>

      <%= link_to 'Books', books_path, class: 'btn btn-primary' %>
      <%= link_to 'Authors', authors_path, class: 'btn btn-info' %>

  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row main text-center" style="color: #000";>

    <h1>Editing Book</h1>

    <%= render 'form', book: @book %>

    <%= link_to 'Show', @book, class: 'btn btn-primary' %>
    <%= link_to 'Back', books_path, class: 'btn btn-info' %>

  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row main">
  <!-- <div class="row main"> -->

    <p id="notice"><%= notice %></p>

    <div class="panel-heading">

      <h1>All Our Books</h1>

      <!-- <table class="table table-striped table-hover"> -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.order(:title).each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <!-- <td><%= book.author_id %></td> -->
              <td><%= book.author.name %></td>
              <td><%= link_to 'Show', book, class: 'btn btn-default' %></td>
              <td><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning' %></td>
              <td><%= link_to 'Destroy', book, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Book', new_book_path, class: 'btn btn-primary' %>
      <%= link_to 'Authors', authors_path, class: 'btn btn-info' %>

    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row main text-center">

    <h1>New Book</h1>

    <%= render 'form', book: @book %>

    <%= link_to 'Cancel', books_path, class: 'btn btn-primary' %>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row main text-center">

    <p id="notice"><%= notice %></p>

    <h1>Viewing Book Details</h1>
    <p>
      <strong>Title:</strong>
      <%= @book.title %>
    </p>

    <p>
      <strong>Author:</strong>
      <!-- <%= @book.author_id %> -->
      <%= @book.author.name %>
    </p>

    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-primary' %>
    <%= link_to 'Back', books_path, class: 'btn btn-info' %>

  </div>
</div>

app/views/books/welcome.html.erb
<!-- <div class="container-fluid">
  <div class="row welcome">

    <%#= render 'layouts/navbar' %>

    <h1>Welcome to Yvette's Library, <%#= current_user.name %>!</h1><br>
    <h1>This is the welcome page.</h1>

    <%#= link_to 'New Book', new_book_path, class: 'btn btn-primary' %>

  </div>

</div> -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="#">
        <%= link_to root_path do %>
        <%= image_tag("bw-books.png", size: "50") %>
        <% end %>
      </a>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Books", books_path %></li>
        <li><%= link_to "Authors", authors_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
          <!-- add greeting -->
          <li>
            <p class="navbar-text">Welcome to the Library, <%= current_user.name %>!</p>
          </li>
          <!-- show a sign out button -->
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
         </li>

        <% else %>
          <!-- show a sign in button -->
          <li>
            <%= link_to fa_icon('sign-in', text: 'Sign In'), new_user_session_path, id: 'sign_in' %>
          </li>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">

    <title>LibraryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>